name: continuous-integration-workflow.yml

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
     - uses: fwal/setup-swift@v1
       with:
        swift-version: "5.5.0"   
     - name: Get swift version
       run: swift --version
      
     - uses: actions/checkout@v2
     - name: Build
       run: swift build -v
     - name: Run tests
       run: swift test -v
